version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/backend"
    schedule:
      interval: "weekly"
      day: "monday"
    open-pull-requests-limit: 10
    labels:
      - "backend"
      - "dependencies"
    commit-message:
      prefix: "chore(backend):"

  - package-ecosystem: "npm"
    directory: "/frontend/my-react-app"
    schedule:
      interval: "weekly"
      day: "monday"
    open-pull-requests-limit: 10
    labels:
      - "frontend"
      - "dependencies"
    commit-message:
      prefix: "chore(frontend):"

  - package-ecosystem: "npm"
    directory: "/Admin/admin"
    schedule:
      interval: "weekly"
      day: "monday"
    open-pull-requests-limit: 10
    labels:
      - "admin"
      - "dependencies"
    commit-message:
      prefix: "chore(admin):"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
    labels:
      - "github-actions"
      - "dependencies"